[2022-12-03 17:25:27,162] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: homework_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [queued]>
[2022-12-03 17:25:27,175] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: homework_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [queued]>
[2022-12-03 17:25:27,176] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 17:25:27,176] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-03 17:25:27,177] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 17:25:27,187] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2022-12-02 00:00:00+00:00
[2022-12-03 17:25:27,195] {standard_task_runner.py:52} INFO - Started process 131 to run task
[2022-12-03 17:25:27,208] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'homework_dag', 'download_dataset_task', 'scheduled__2022-12-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/homework_dag.py', '--cfg-path', '/tmp/tmps40h044j', '--error-file', '/tmp/tmp_67587ks']
[2022-12-03 17:25:27,209] {standard_task_runner.py:77} INFO - Job 3: Subtask download_dataset_task
[2022-12-03 17:25:27,261] {logging_mixin.py:109} INFO - Running <TaskInstance: homework_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [running]> on host 48f7180843d2
[2022-12-03 17:25:27,322] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=homework_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T00:00:00+00:00
[2022-12-03 17:25:40,297] {python.py:175} INFO - Done. Returned value was: None
[2022-12-03 17:25:40,397] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=homework_dag, task_id=download_dataset_task, execution_date=20221202T000000, start_date=20221203T172527, end_date=20221203T172540
[2022-12-03 17:25:40,536] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-12-03 17:25:40,550] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 131. PIDs of all processes in the group: [131]
[2022-12-03 17:25:40,551] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 131
[2022-12-03 17:25:40,684] {process_utils.py:70} INFO - Process psutil.Process(pid=131, status='terminated', exitcode=0, started='17:25:26') (131) terminated with exit code 0
