[2022-12-22 09:14:26,994] {processor.py:163} INFO - Started process (PID=38) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:14:26,997] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:14:27,008] {logging_mixin.py:109} INFO - [2022-12-22 09:14:27,008] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:14:27,009] {processor.py:163} INFO - Started process (PID=37) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:14:27,011] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:14:27,014] {logging_mixin.py:109} INFO - [2022-12-22 09:14:27,014] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:14:29,793] {logging_mixin.py:109} INFO - [2022-12-22 09:14:29,747] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:14:29,846] {logging_mixin.py:109} INFO - [2022-12-22 09:14:29,793] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:14:29,910] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:14:29,915] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:14:29,981] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 2.986 seconds
[2022-12-22 09:14:29,988] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:14:29,989] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:14:30,015] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 3.028 seconds
[2022-12-22 09:15:00,596] {processor.py:163} INFO - Started process (PID=65) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:00,613] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:15:00,624] {logging_mixin.py:109} INFO - [2022-12-22 09:15:00,624] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:00,756] {processor.py:163} INFO - Started process (PID=64) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:00,762] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:15:00,771] {logging_mixin.py:109} INFO - [2022-12-22 09:15:00,770] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:05,505] {logging_mixin.py:109} INFO - [2022-12-22 09:15:05,460] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:15:05,629] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:05,675] {logging_mixin.py:109} INFO - [2022-12-22 09:15:05,644] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:15:05,677] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 5.121 seconds
[2022-12-22 09:15:05,719] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:05,732] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 5.012 seconds
[2022-12-22 09:15:35,783] {processor.py:163} INFO - Started process (PID=99) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:35,784] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:15:35,785] {logging_mixin.py:109} INFO - [2022-12-22 09:15:35,785] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:35,797] {processor.py:163} INFO - Started process (PID=92) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:35,798] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:15:35,799] {logging_mixin.py:109} INFO - [2022-12-22 09:15:35,799] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:36,337] {logging_mixin.py:109} INFO - [2022-12-22 09:15:36,332] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:15:36,349] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:36,356] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.563 seconds
[2022-12-22 09:15:36,363] {logging_mixin.py:109} INFO - [2022-12-22 09:15:36,359] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:15:36,376] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:15:36,383] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.603 seconds
[2022-12-22 09:16:06,491] {processor.py:163} INFO - Started process (PID=129) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:06,493] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:16:06,494] {logging_mixin.py:109} INFO - [2022-12-22 09:16:06,494] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:06,503] {processor.py:163} INFO - Started process (PID=126) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:06,505] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:16:06,505] {logging_mixin.py:109} INFO - [2022-12-22 09:16:06,505] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:07,077] {logging_mixin.py:109} INFO - [2022-12-22 09:16:07,073] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:16:07,082] {logging_mixin.py:109} INFO - [2022-12-22 09:16:07,078] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:16:07,090] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:07,094] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:07,103] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.603 seconds
[2022-12-22 09:16:07,103] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.615 seconds
[2022-12-22 09:16:37,141] {processor.py:163} INFO - Started process (PID=162) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:37,143] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:16:37,144] {logging_mixin.py:109} INFO - [2022-12-22 09:16:37,143] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:37,225] {processor.py:163} INFO - Started process (PID=165) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:37,230] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:16:37,231] {logging_mixin.py:109} INFO - [2022-12-22 09:16:37,231] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:37,590] {logging_mixin.py:109} INFO - [2022-12-22 09:16:37,584] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:16:37,604] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:37,612] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.479 seconds
[2022-12-22 09:16:37,659] {logging_mixin.py:109} INFO - [2022-12-22 09:16:37,652] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:16:37,670] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:16:37,676] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.458 seconds
[2022-12-22 09:17:07,742] {processor.py:163} INFO - Started process (PID=198) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:07,744] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:17:07,745] {logging_mixin.py:109} INFO - [2022-12-22 09:17:07,744] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:07,804] {processor.py:163} INFO - Started process (PID=192) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:07,806] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:17:07,806] {logging_mixin.py:109} INFO - [2022-12-22 09:17:07,806] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:08,205] {logging_mixin.py:109} INFO - [2022-12-22 09:17:08,200] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:17:08,218] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:08,224] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.485 seconds
[2022-12-22 09:17:08,270] {logging_mixin.py:109} INFO - [2022-12-22 09:17:08,266] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:17:08,283] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:08,289] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.487 seconds
[2022-12-22 09:17:38,368] {processor.py:163} INFO - Started process (PID=225) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:38,369] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:17:38,369] {logging_mixin.py:109} INFO - [2022-12-22 09:17:38,369] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:38,451] {processor.py:163} INFO - Started process (PID=228) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:38,455] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:17:38,455] {logging_mixin.py:109} INFO - [2022-12-22 09:17:38,455] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:38,741] {logging_mixin.py:109} INFO - [2022-12-22 09:17:38,735] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:17:38,756] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:38,765] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.400 seconds
[2022-12-22 09:17:38,869] {logging_mixin.py:109} INFO - [2022-12-22 09:17:38,864] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:17:38,882] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:17:38,891] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.442 seconds
[2022-12-22 09:18:08,955] {processor.py:163} INFO - Started process (PID=259) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:08,961] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:18:08,964] {logging_mixin.py:109} INFO - [2022-12-22 09:18:08,964] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:09,744] {logging_mixin.py:109} INFO - [2022-12-22 09:18:09,741] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:18:09,759] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:09,768] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.834 seconds
[2022-12-22 09:18:32,053] {processor.py:163} INFO - Started process (PID=29) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:32,054] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:18:32,055] {logging_mixin.py:109} INFO - [2022-12-22 09:18:32,055] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:34,478] {logging_mixin.py:109} INFO - [2022-12-22 09:18:34,474] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:18:34,502] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:34,516] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 2.466 seconds
[2022-12-22 09:18:40,499] {processor.py:163} INFO - Started process (PID=288) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:40,508] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:18:40,516] {logging_mixin.py:109} INFO - [2022-12-22 09:18:40,515] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:43,121] {logging_mixin.py:109} INFO - [2022-12-22 09:18:43,113] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:18:43,139] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:18:43,149] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 2.731 seconds
[2022-12-22 09:19:04,766] {processor.py:163} INFO - Started process (PID=64) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:04,768] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:19:04,771] {logging_mixin.py:109} INFO - [2022-12-22 09:19:04,771] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:05,435] {logging_mixin.py:109} INFO - [2022-12-22 09:19:05,430] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:19:05,449] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:05,458] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.704 seconds
[2022-12-22 09:19:13,269] {processor.py:163} INFO - Started process (PID=324) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:13,271] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:19:13,272] {logging_mixin.py:109} INFO - [2022-12-22 09:19:13,272] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:13,717] {logging_mixin.py:109} INFO - [2022-12-22 09:19:13,711] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:19:13,732] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:13,739] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.473 seconds
[2022-12-22 09:19:35,620] {processor.py:163} INFO - Started process (PID=100) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:35,621] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:19:35,622] {logging_mixin.py:109} INFO - [2022-12-22 09:19:35,622] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:36,080] {logging_mixin.py:109} INFO - [2022-12-22 09:19:36,074] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:19:36,093] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:36,102] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.484 seconds
[2022-12-22 09:19:43,915] {processor.py:163} INFO - Started process (PID=351) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:43,916] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:19:43,917] {logging_mixin.py:109} INFO - [2022-12-22 09:19:43,917] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:44,475] {logging_mixin.py:109} INFO - [2022-12-22 09:19:44,470] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:19:44,489] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:19:44,497] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.585 seconds
[2022-12-22 09:20:06,216] {processor.py:163} INFO - Started process (PID=127) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:20:06,218] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:20:06,219] {logging_mixin.py:109} INFO - [2022-12-22 09:20:06,219] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:20:06,644] {logging_mixin.py:109} INFO - [2022-12-22 09:20:06,639] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:20:06,656] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:20:06,665] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.452 seconds
[2022-12-22 09:31:07,131] {processor.py:163} INFO - Started process (PID=38) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:31:07,133] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:31:07,135] {logging_mixin.py:109} INFO - [2022-12-22 09:31:07,135] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:31:10,870] {logging_mixin.py:109} INFO - [2022-12-22 09:31:10,838] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:31:10,961] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:31:10,990] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 3.865 seconds
[2022-12-22 09:31:41,734] {processor.py:163} INFO - Started process (PID=65) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:31:41,738] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:31:41,740] {logging_mixin.py:109} INFO - [2022-12-22 09:31:41,739] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:31:42,268] {logging_mixin.py:109} INFO - [2022-12-22 09:31:42,261] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:31:42,285] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:31:42,295] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.573 seconds
[2022-12-22 09:32:12,411] {processor.py:163} INFO - Started process (PID=101) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:32:12,412] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:32:12,413] {logging_mixin.py:109} INFO - [2022-12-22 09:32:12,413] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:32:12,812] {logging_mixin.py:109} INFO - [2022-12-22 09:32:12,808] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:32:12,824] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:32:12,831] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.424 seconds
[2022-12-22 09:32:42,963] {processor.py:163} INFO - Started process (PID=129) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:32:42,964] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:32:42,965] {logging_mixin.py:109} INFO - [2022-12-22 09:32:42,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:32:43,407] {logging_mixin.py:109} INFO - [2022-12-22 09:32:43,401] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:32:43,421] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:32:43,429] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.468 seconds
[2022-12-22 09:34:06,713] {processor.py:163} INFO - Started process (PID=38) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:34:06,715] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:34:06,719] {logging_mixin.py:109} INFO - [2022-12-22 09:34:06,719] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:34:11,804] {logging_mixin.py:109} INFO - [2022-12-22 09:34:11,774] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:34:11,875] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:34:11,894] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 5.184 seconds
[2022-12-22 09:34:43,012] {processor.py:163} INFO - Started process (PID=65) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:34:43,020] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:34:43,034] {logging_mixin.py:109} INFO - [2022-12-22 09:34:43,033] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:34:43,981] {logging_mixin.py:109} INFO - [2022-12-22 09:34:43,961] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:34:44,014] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:34:44,035] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 1.057 seconds
[2022-12-22 09:35:14,162] {processor.py:163} INFO - Started process (PID=101) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:35:14,163] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:35:14,165] {logging_mixin.py:109} INFO - [2022-12-22 09:35:14,164] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:35:14,570] {logging_mixin.py:109} INFO - [2022-12-22 09:35:14,563] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:35:14,582] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:35:14,589] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.430 seconds
[2022-12-22 09:35:44,709] {processor.py:163} INFO - Started process (PID=137) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:35:44,711] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:35:44,712] {logging_mixin.py:109} INFO - [2022-12-22 09:35:44,711] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:35:45,136] {logging_mixin.py:109} INFO - [2022-12-22 09:35:45,133] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:35:45,157] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:35:45,165] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.459 seconds
[2022-12-22 09:36:15,301] {processor.py:163} INFO - Started process (PID=164) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:36:15,302] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:36:15,303] {logging_mixin.py:109} INFO - [2022-12-22 09:36:15,303] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:36:15,875] {logging_mixin.py:109} INFO - [2022-12-22 09:36:15,871] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:36:15,887] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:36:15,898] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.600 seconds
[2022-12-22 09:36:45,979] {processor.py:163} INFO - Started process (PID=200) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:36:45,980] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:36:45,981] {logging_mixin.py:109} INFO - [2022-12-22 09:36:45,981] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:36:46,368] {logging_mixin.py:109} INFO - [2022-12-22 09:36:46,362] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:36:46,382] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:36:46,404] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.428 seconds
[2022-12-22 09:37:16,529] {processor.py:163} INFO - Started process (PID=227) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:37:16,530] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:37:16,531] {logging_mixin.py:109} INFO - [2022-12-22 09:37:16,530] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:37:16,914] {logging_mixin.py:109} INFO - [2022-12-22 09:37:16,910] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:37:16,925] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:37:16,932] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.407 seconds
[2022-12-22 09:37:47,067] {processor.py:163} INFO - Started process (PID=262) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:37:47,068] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:37:47,069] {logging_mixin.py:109} INFO - [2022-12-22 09:37:47,069] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:37:47,462] {logging_mixin.py:109} INFO - [2022-12-22 09:37:47,457] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:37:47,475] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:37:47,482] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.419 seconds
[2022-12-22 09:38:17,593] {processor.py:163} INFO - Started process (PID=298) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:38:17,595] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:38:17,596] {logging_mixin.py:109} INFO - [2022-12-22 09:38:17,596] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:38:18,140] {logging_mixin.py:109} INFO - [2022-12-22 09:38:18,136] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/fireflow_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fireflow_batch_dag.py", line 11, in <module>
    from airflow_dbt.operators.dbt_operator import DbtRunOperator, DbtTestOperator
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-12-22 09:38:18,153] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:38:18,159] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.570 seconds
[2022-12-22 09:38:28,272] {processor.py:163} INFO - Started process (PID=307) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:38:28,274] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:38:28,282] {logging_mixin.py:109} INFO - [2022-12-22 09:38:28,281] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:38:30,253] {processor.py:654} INFO - DAG(s) dict_keys(['fireflow_dag']) retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:38:30,929] {logging_mixin.py:109} INFO - [2022-12-22 09:38:30,929] {dag.py:2396} INFO - Sync 1 DAGs
[2022-12-22 09:38:30,968] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 2.711 seconds
[2022-12-22 09:39:01,107] {processor.py:163} INFO - Started process (PID=343) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:39:01,108] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:39:01,109] {logging_mixin.py:109} INFO - [2022-12-22 09:39:01,109] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:39:01,766] {processor.py:654} INFO - DAG(s) dict_keys(['fireflow_dag']) retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:39:01,778] {logging_mixin.py:109} INFO - [2022-12-22 09:39:01,777] {dag.py:2396} INFO - Sync 1 DAGs
[2022-12-22 09:39:01,796] {logging_mixin.py:109} INFO - [2022-12-22 09:39:01,795] {dag.py:2935} INFO - Setting next_dagrun for fireflow_dag to 2022-12-21T10:00:00+00:00
[2022-12-22 09:39:01,807] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.703 seconds
[2022-12-22 09:43:12,922] {processor.py:163} INFO - Started process (PID=35) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:43:12,923] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:43:12,924] {logging_mixin.py:109} INFO - [2022-12-22 09:43:12,924] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:43:17,209] {processor.py:654} INFO - DAG(s) dict_keys(['fireflow_dag']) retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:43:18,403] {logging_mixin.py:109} INFO - [2022-12-22 09:43:18,403] {dag.py:2396} INFO - Sync 1 DAGs
[2022-12-22 09:43:18,429] {logging_mixin.py:109} INFO - [2022-12-22 09:43:18,428] {dag.py:2935} INFO - Setting next_dagrun for fireflow_dag to 2022-12-21T10:00:00+00:00
[2022-12-22 09:43:18,599] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 5.680 seconds
[2022-12-22 09:43:49,507] {processor.py:163} INFO - Started process (PID=65) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:43:49,510] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:43:49,512] {logging_mixin.py:109} INFO - [2022-12-22 09:43:49,512] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:43:50,402] {processor.py:654} INFO - DAG(s) dict_keys(['fireflow_dag']) retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:43:50,411] {logging_mixin.py:109} INFO - [2022-12-22 09:43:50,411] {dag.py:2396} INFO - Sync 1 DAGs
[2022-12-22 09:43:50,427] {logging_mixin.py:109} INFO - [2022-12-22 09:43:50,426] {dag.py:2935} INFO - Setting next_dagrun for fireflow_dag to 2022-12-21T10:00:00+00:00
[2022-12-22 09:43:50,441] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 0.944 seconds
[2022-12-22 09:44:20,571] {processor.py:163} INFO - Started process (PID=102) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:44:20,573] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:44:20,574] {logging_mixin.py:109} INFO - [2022-12-22 09:44:20,574] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:44:21,582] {processor.py:654} INFO - DAG(s) dict_keys(['fireflow_dag']) retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:44:21,594] {logging_mixin.py:109} INFO - [2022-12-22 09:44:21,593] {dag.py:2396} INFO - Sync 1 DAGs
[2022-12-22 09:44:21,610] {logging_mixin.py:109} INFO - [2022-12-22 09:44:21,610] {dag.py:2935} INFO - Setting next_dagrun for fireflow_dag to 2022-12-21T10:00:00+00:00
[2022-12-22 09:44:21,622] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 1.054 seconds
[2022-12-22 09:44:51,707] {processor.py:163} INFO - Started process (PID=129) to work on /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:44:51,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/fireflow_batch_dag.py for tasks to queue
[2022-12-22 09:44:51,710] {logging_mixin.py:109} INFO - [2022-12-22 09:44:51,710] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:44:52,751] {processor.py:654} INFO - DAG(s) dict_keys(['fireflow_dag']) retrieved from /opt/airflow/dags/fireflow_batch_dag.py
[2022-12-22 09:44:52,769] {logging_mixin.py:109} INFO - [2022-12-22 09:44:52,768] {dag.py:2396} INFO - Sync 1 DAGs
[2022-12-22 09:44:52,802] {logging_mixin.py:109} INFO - [2022-12-22 09:44:52,801] {dag.py:2935} INFO - Setting next_dagrun for fireflow_dag to 2022-12-21T10:00:00+00:00
[2022-12-22 09:44:52,824] {processor.py:171} INFO - Processing /opt/airflow/dags/fireflow_batch_dag.py took 1.120 seconds
